# Brazilian&nbsp;E-commers&nbsp;Data&nbsp;Visualization

### Importing libraries to use and connect to the DataBase

In [1]:
import math
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import psycopg2
import seaborn as sns
import folium  #needed for interactive map
from folium.plugins import HeatMap

# CONNECTION TO THE DATABASE
try:
    conn = psycopg2.connect(
        host = "ec2-54-157-79-121.compute-1.amazonaws.com",
        database = "d42ekpicafpt4b",
        user = "okskipddgcuaix",
        password = "f4389a6257140d0f66be8163b27d131299ec2aa73455aa07991669ea689eb008"
        )

    print("Successful connection")
    #cursor = conn.cursor()
    #row = cursor.fetchone()
    #print(row)

except Exception as ex:
    print(ex)

Successful connection


### Select Payment Table

In [2]:
order_payments_table = "SELECT * FROM order_payments_table"

### Transform to dataset

In [3]:
dfPayments = pd.io.sql.read_sql_query(order_payments_table, conn)

### Cual es el promedio de cuotas se pagan según el método de pago?

In [4]:
dfAgrupado = dfPayments.groupby('payment_type')['payment_installments'].mean()
print(dfAgrupado)

payment_type
boleto         1.000000
credit_card    3.507155
debit_card     1.000000
not_defined    1.000000
voucher        1.000000
Name: payment_installments, dtype: float64


Se observa con la agrupación y el promedio (media) que el único método de pago utilizado para pagar mas de una (1) cuota es tarjeta de crédito "credit_card". Esta observación nos indica que el método de pago que se puede analizar es el de tarjeta de crédito.

### Cuanto es el mínimo, máximo, mediana de cuotas que se pagan con tarjeta de crédito?

In [5]:
dfCreditCard = dfPayments[dfPayments['payment_type'] == 'credit_card'].sort_values('payment_installments', ascending=1)
dfCreditCard = dfCreditCard[dfCreditCard['payment_installments'] > 0]
min = dfCreditCard['payment_installments'].min()
max = dfCreditCard['payment_installments'].max()
valores = dfCreditCard['payment_installments'].unique()
median = np.median(valores)
print(min, max, median)
print(dfCreditCard)

1 24 12.0
          id  order_id  payment_sequential payment_type  payment_installments  \
46458  46459     45333                   1  credit_card                     1   
46460  46461     45335                   1  credit_card                     1   
46461  46462     45336                   1  credit_card                     1   
96843  96844     92879                   1  credit_card                     1   
46465  46466     45340                   1  credit_card                     1   
...      ...       ...                 ...          ...                   ...   
55094  55095     53561                   1  credit_card                    24   
12307  12308     12201                   1  credit_card                    24   
2970    2971      2964                   1  credit_card                    24   
36088  36089     35381                   1  credit_card                    24   
10791  10792     10709                   1  credit_card                    24   

       payment_va

Se observa que el mínimo de cuotas es: 1 (una) cuota; el máximo de cuotas es de 24 (veinticuatro) cuotas; la mediana de cuotas es de 12 (doce) cuotas para el método de pago tarjeta de crédito

### Cuantos pagos se realizaron según el número de cuotas?

In [6]:
df = dfCreditCard.groupby('payment_installments')['id'].count()
print(df)

payment_installments
1     25455
2     12413
3     10461
4      7098
5      5239
6      3920
7      1626
8      4268
9       644
10     5328
11       23
12      133
13       16
14       15
15       74
16        5
17        8
18       27
20       17
21        3
22        1
23        1
24       18
Name: id, dtype: int64


Se observa que se realizaron 25455 pagos de una cuota, 12413 pago de dos cuotas y así sucesivamente.

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=52e324f1-f7f5-4caa-9d11-b7c0b4fab5ac' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>